"""Persian RAG administrative assistant — Streamlit UI.

Single-file build of frontend/ — generated by scripts/build_standalone.py, do not edit by hand.
Settings are read from a .env file next to this file.

Run:  python frontend_app.py
"""
from datetime import datetime
import html
import os
from pathlib import Path
import sys
from typing import Any

from dotenv import load_dotenv
import httpx
import streamlit as st
from streamlit import runtime


# ==================================================================================================
# frontend/config.py — Frontend settings, read from the project's root .env file.
# ==================================================================================================
ROOT_DIR = Path(__file__).resolve().parent
load_dotenv(ROOT_DIR / ".env")

BACKEND_URL = os.getenv("BACKEND_URL", "http://127.0.0.1:8000").rstrip("/")
REQUEST_TIMEOUT = float(os.getenv("FRONTEND_REQUEST_TIMEOUT", "300"))
DEFAULT_TEMPERATURE = float(os.getenv("FRONTEND_DEFAULT_TEMPERATURE", "0.2"))
MAX_TEMPERATURE = float(os.getenv("FRONTEND_MAX_TEMPERATURE", "1.5"))
HEALTH_CACHE_SECONDS = int(os.getenv("FRONTEND_HEALTH_CACHE_SECONDS", "15"))

if __name__ == "__main__" and not runtime.exists():
    # `python frontend_app.py` re-runs this file under Streamlit with the port/address from .env
    os.execv(sys.executable, [
        sys.executable, "-m", "streamlit", "run", __file__,
        "--server.port", os.getenv("FRONTEND_PORT", "8501"),
        "--server.address", os.getenv("FRONTEND_HOST", "0.0.0.0"),
        "--server.headless", "true",
        "--browser.gatherUsageStats", "false",
        "--theme.primaryColor", "#1f5eb8",
    ])


# ==================================================================================================
# frontend/texts.py — All Persian UI strings in one place — edit here to change wording.
# ==================================================================================================
class T:
    """All Persian UI strings in one place — edit here to change wording."""

    APP_TITLE = "دستیار اداری هوشمند"
    NAV_CHAT = "گفتگو"
    NAV_ADMIN = "مدیریت اسناد"

    # ---------- sidebar ----------
    STATUS_TITLE = "وضعیت سرویس"
    STATUS_READY = "آماده"
    STATUS_LLM_DOWN = "مدل زبانی در دسترس نیست"
    STATUS_BACKEND_DOWN = "سرور در دسترس نیست"
    STATUS_CHUNKS = "{n} قطعه در پایگاه دانش"
    STATUS_REFRESH = "بررسی مجدد"

    # ---------- chat ----------
    CHAT_TITLE = "گفتگو با دستیار"
    CHAT_INTRO = (
        "پرسش خود را درباره‌ی آیین‌نامه‌ها، بخشنامه‌ها و امور اداری بنویسید. "
        "پاسخ‌ها فقط بر اساس اسناد ثبت‌شده ارائه می‌شوند."
    )
    CHAT_SUGGESTIONS = [
        "مرخصی استحقاقی سالانه چند روز است؟",
        "روند ثبت درخواست مأموریت چیست؟",
        "نرخ امروز دلار چقدر است؟",
    ]
    CHAT_PLACEHOLDER = "پیام خود را بنویسید…"
    CHAT_THINKING = "در حال جستجو و تهیه‌ی پاسخ…"
    CHAT_SETTINGS = "تنظیمات گفتگو"
    CHAT_TEMPERATURE = "دما (Temperature)"
    CHAT_TEMPERATURE_HELP = "دمای کمتر = پاسخ دقیق‌تر و ثابت‌تر · دمای بیشتر = پاسخ متنوع‌تر. این تنظیم فقط روی گفتگوی شما اثر دارد."
    CHAT_CLEAR = "پاک کردن گفتگو"
    CHAT_DISCLAIMER = "پاسخ‌ها را پیش از استفاده‌ی رسمی بررسی کنید."

    SOURCE_BADGES = {
        "documents": ":green-badge[پاسخ از اسناد]",
        "model": ":violet-badge[پاسخ از دانش مدل]",
        "web": ":blue-badge[پاسخ از جستجوی وب]",
        "none": ":orange-badge[پاسخی یافت نشد]",
    }
    TEMPERATURE_CAPTION = "دما {t}"
    SOURCES_TITLE = "منابع ({n})"
    WEB_SOURCES_TITLE = "منابع جستجوی وب:"
    SOURCE_PAGE = "صفحه {p}"
    SOURCE_SCORE = "شباهت {s}٪"
    SOURCE_UNTITLED = "بدون عنوان"

    # ---------- admin ----------
    ADMIN_TITLE = "مدیریت اسناد"
    ADMIN_LOGIN_TITLE = "ورود مدیر"
    ADMIN_LOGIN_HELP = "برای بارگذاری و حذف اسناد، کلید مدیر (ADMIN_API_KEY) را وارد کنید."
    ADMIN_KEY_LABEL = "کلید مدیر"
    ADMIN_LOGIN = "ورود"
    ADMIN_LOGOUT = "خروج"
    ADMIN_KEY_EMPTY = "کلید مدیر را وارد کنید."

    UPLOAD_TITLE = "بارگذاری اسناد"
    UPLOAD_LABEL = "فایل‌های PDF، DOCX یا TXT را انتخاب کنید"
    UPLOAD_BUTTON = "بارگذاری و پردازش"
    UPLOAD_PROGRESS = "در حال پردازش {n} فایل… (ممکن است برای فایل‌های بزرگ چند دقیقه طول بکشد)"
    UPLOAD_CHUNKS = " ({n} قطعه)"

    DOCS_TITLE = "اسناد ثبت‌شده"
    DOCS_COUNT = "{n} سند"
    DOCS_EMPTY = "هنوز سندی بارگذاری نشده است."
    DOCS_REFRESH = "بروزرسانی"
    DOCS_COL_NAME = "نام فایل"
    DOCS_COL_CHUNKS = "تعداد قطعه"
    DOCS_COL_DATE = "تاریخ بارگذاری"
    DOCS_DELETE = "حذف"
    DOCS_DELETE_CONFIRM = "سند «{name}» از پایگاه دانش حذف شود؟"
    DOCS_DELETE_YES = "بله، حذف شود"
    DOCS_DELETE_NO = "انصراف"

    # ---------- errors (network-level; API errors come in Persian from the backend) ----------
    ERR_CONNECTION = "ارتباط با سرور برقرار نشد. اجرای سرویس بک‌اند و آدرس BACKEND_URL را بررسی کنید."
    ERR_TIMEOUT = "زمان پاسخ‌گویی سرور به پایان رسید. لطفاً دوباره تلاش کنید."
    ERR_UNKNOWN = "خطای ناشناخته از سرور دریافت شد."


# ==================================================================================================
# frontend/ui/formatting.py — Small display helpers shared by the pages.
# ==================================================================================================
_FA_DIGITS = str.maketrans("0123456789.", "۰۱۲۳۴۵۶۷۸۹٫")


def fa(value) -> str:
    """Render a number with Persian digits."""
    return str(value).translate(_FA_DIGITS)


def md_safe(text: str) -> str:
    """Stop Streamlit from treating $...$ in answers (e.g. prices) as LaTeX."""
    return text.replace("$", r"\$")


def esc(text) -> str:
    return html.escape(str(text or ""))


def fa_datetime(iso: str) -> str:
    try:
        dt = datetime.fromisoformat(iso).astimezone()
    except ValueError:
        return iso
    return fa(dt.strftime("%Y/%m/%d %H:%M"))


# ==================================================================================================
# frontend/api_client.py — Thin HTTP client for the FastAPI backend. All network calls from the UI go through here.
# ==================================================================================================
class ApiError(Exception):
    def __init__(self, message: str, status: int | None = None, errors: list[dict] | None = None):
        super().__init__(message)
        self.message = message
        self.status = status
        self.errors = errors or []


def _request(method: str, path: str, admin_key: str | None = None, timeout: float | None = None, **kwargs) -> Any:
    headers = kwargs.pop("headers", {})
    if admin_key:
        headers["X-Admin-Key"] = admin_key
    try:
        response = httpx.request(
            method, f"{BACKEND_URL}{path}", headers=headers, timeout=timeout or REQUEST_TIMEOUT, **kwargs
        )
    except httpx.TimeoutException as exc:
        raise ApiError(T.ERR_TIMEOUT) from exc
    except httpx.HTTPError as exc:
        raise ApiError(T.ERR_CONNECTION) from exc

    try:
        data = response.json()
    except ValueError:
        data = None
    if response.is_error:
        detail = data.get("detail") if isinstance(data, dict) else None
        errors = data.get("errors") if isinstance(data, dict) else None
        raise ApiError(detail if isinstance(detail, str) else T.ERR_UNKNOWN, response.status_code, errors)
    return data


def health() -> dict:
    return _request("GET", "/health", timeout=5)


def chat(message: str, temperature: float) -> dict:
    return _request("POST", "/chat", json={"message": message, "temperature": temperature})


def list_documents(admin_key: str) -> list[dict]:
    return _request("GET", "/admin/documents", admin_key=admin_key)


def upload_documents(admin_key: str, files: list[tuple[str, bytes, str]]) -> dict:
    """files: list of (filename, content, mime_type)."""
    return _request("POST", "/admin/upload", admin_key=admin_key, files=[("files", f) for f in files])


def delete_document(admin_key: str, doc_id: str) -> dict:
    return _request("DELETE", f"/admin/documents/{doc_id}", admin_key=admin_key)


# ==================================================================================================
# frontend/ui/style.py + frontend/assets/style.css
# ==================================================================================================
CSS = """
/* RTL + Persian font for the Streamlit UI. Edit freely — loaded on every page by ui/style.py */
@import url("https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;700&display=swap");

:root {
  --fa-font: "Vazirmatn", Tahoma, "Segoe UI", sans-serif;
}

/* Font: set on containers only, so Streamlit's icon font keeps working */
.stApp, .stMarkdown, .stChatMessage, .stAlert, button, input, textarea, label,
h1, h2, h3, h4, [data-testid="stCaptionContainer"], [data-testid="stSidebarNav"] {
  font-family: var(--fa-font) !important;
}

/* Right-to-left text */
.stMarkdown, .stChatMessage, .stAlert, label, h1, h2, h3, h4,
[data-testid="stCaptionContainer"], [data-testid="stExpander"], [data-testid="stSidebar"],
[data-testid="stFileUploader"], [data-testid="stForm"] {
  direction: rtl;
  text-align: right;
}
textarea, input[type="text"] {
  direction: rtl;
  text-align: right;
}
/* The admin key is Latin — keep it LTR */
input[type="password"] {
  direction: ltr;
  text-align: left;
}

/* Chat */
.stChatMessage {
  line-height: 1.9;
}
.stChatMessage ul, .stChatMessage ol {
  padding-right: 1.4rem;
  padding-left: 0;
}
.source-item {
  background: rgba(127, 127, 127, .08);
  border-radius: 8px;
  padding: .45rem .7rem;
  margin-bottom: .45rem;
  font-size: .9rem;
}
.source-item .snippet {
  opacity: .75;
  font-size: .82rem;
  margin-top: .15rem;
}
.source-item a {
  direction: ltr;
  unicode-bidi: embed;
  word-break: break-all;
}

/* Status dot in sidebar */
.status-dot {
  display: inline-block;
  width: .6rem;
  height: .6rem;
  border-radius: 50%;
  margin-left: .4rem;
}
.status-dot.ok { background: #1a8a4a; }
.status-dot.warn { background: #d69e2e; }
.status-dot.err { background: #c53030; }
"""


def inject_style() -> None:
    st.html("<style>" + CSS + "</style>")


# ==================================================================================================
# frontend/ui/sidebar.py — Sidebar content shared by every page: service status.
# ==================================================================================================
@st.cache_data(ttl=HEALTH_CACHE_SECONDS, show_spinner=False)
def _health() -> dict | None:
    try:
        return health()
    except ApiError:
        return None


def render_sidebar() -> None:
    with st.sidebar:
        st.subheader(T.STATUS_TITLE)
        h = _health()
        if h is None:
            dot, text = "err", T.STATUS_BACKEND_DOWN
        elif not h.get("llm_available"):
            dot, text = "warn", T.STATUS_LLM_DOWN
        else:
            dot, text = "ok", T.STATUS_READY
        st.html(f'<div dir="rtl"><span class="status-dot {dot}"></span>{text}</div>')
        if h is not None:
            st.caption(T.STATUS_CHUNKS.format(n=fa(h.get("indexed_chunks", 0))))
        if st.button(T.STATUS_REFRESH, icon=":material/refresh:", width="stretch"):
            _health.clear()
            st.rerun()
        st.divider()


def invalidate_health() -> None:
    _health.clear()


# ==================================================================================================
# frontend/ui/chat_page.py — Chat page — regular users. History and temperature live in this browser session only.
# ==================================================================================================
def _sidebar_settings() -> None:
    with st.sidebar:
        st.subheader(T.CHAT_SETTINGS)
        # Stored in st.session_state => independent for every user/browser tab
        st.slider(
            T.CHAT_TEMPERATURE, min_value=0.0, max_value=MAX_TEMPERATURE, step=0.05,
            value=DEFAULT_TEMPERATURE, key="temperature", help=T.CHAT_TEMPERATURE_HELP,
        )
        if st.button(T.CHAT_CLEAR, icon=":material/delete_sweep:", width="stretch"):
            st.session_state.messages = []
            st.rerun()


def _render_sources(sources: list[dict], source: str) -> None:
    if not sources:
        return
    if source == "web":
        # Web answers: the answer comes first, then just the search results as links
        items = []
        for i, s in enumerate(sources, start=1):
            title = esc(s.get("title") or T.SOURCE_UNTITLED)
            url = esc(s.get("url") or "")
            link = f'<a href="{url}" target="_blank" rel="noopener noreferrer">{title}</a>' if url else title
            items.append(f'<div class="source-item" dir="rtl">{fa(i)}. {link}</div>')
        st.html(f'<div dir="rtl"><b>{T.WEB_SOURCES_TITLE}</b></div>' + "".join(items))
        return
    with st.expander(T.SOURCES_TITLE.format(n=fa(len(sources)))):
        items = []
        for i, s in enumerate(sources, start=1):
            parts = [f"<b>{fa(i)}. {esc(s.get('title') or T.SOURCE_UNTITLED)}</b>"]
            if s.get("page"):
                parts.append(T.SOURCE_PAGE.format(p=fa(s["page"])))
            if s.get("score") is not None and not s.get("url"):
                parts.append(T.SOURCE_SCORE.format(s=fa(round(s["score"] * 100))))
            if s.get("url"):
                url = esc(s["url"])
                parts.append(f'<a href="{url}" target="_blank" rel="noopener noreferrer">{url}</a>')
            snippet = f'<div class="snippet">{esc(s["snippet"])}</div>' if s.get("snippet") else ""
            items.append(f'<div class="source-item" dir="rtl">{" · ".join(parts)}{snippet}</div>')
        st.html("".join(items))


def _render_message(msg: dict) -> None:
    with st.chat_message(msg["role"]):
        if msg.get("error"):
            st.error(msg["content"])
            return
        st.markdown(md_safe(msg["content"]))
        if msg["role"] == "assistant":
            badge = T.SOURCE_BADGES.get(msg.get("source", ""), "")
            st.caption(f"{badge}  {T.TEMPERATURE_CAPTION.format(t=fa(msg.get('temperature', '')))}")
            _render_sources(msg.get("sources", []), msg.get("source", ""))


def _ask(question: str) -> dict:
    temperature = st.session_state.temperature
    try:
        r = chat(question, temperature)
    except ApiError as exc:
        details = "\n".join(f"- {e.get('message')}" for e in exc.errors)
        return {"role": "assistant", "content": exc.message + (f"\n{details}" if details else ""), "error": True}
    return {
        "role": "assistant",
        "content": r["answer"],
        "source": r["source"],
        "sources": r.get("sources", []),
        "temperature": r.get("temperature", temperature),
    }


def render_chat_page() -> None:
    _sidebar_settings()
    messages: list[dict] = st.session_state.setdefault("messages", [])

    st.title(T.CHAT_TITLE)
    if not messages:
        st.info(T.CHAT_INTRO)
        cols = st.columns(len(T.CHAT_SUGGESTIONS))
        for col, suggestion in zip(cols, T.CHAT_SUGGESTIONS):
            if col.button(suggestion, width="stretch"):
                st.session_state.pending_prompt = suggestion
                st.rerun()

    for msg in messages:
        _render_message(msg)

    prompt = st.chat_input(T.CHAT_PLACEHOLDER) or st.session_state.pop("pending_prompt", None)
    if prompt:
        user_msg = {"role": "user", "content": prompt}
        messages.append(user_msg)
        _render_message(user_msg)
        with st.spinner(T.CHAT_THINKING):
            answer = _ask(prompt)
        messages.append(answer)
        _render_message(answer)

    st.caption(T.CHAT_DISCLAIMER)


# ==================================================================================================
# frontend/ui/admin_page.py — Admin page — login with ADMIN_API_KEY, upload, list and delete documents.
# ==================================================================================================
_STATUS_VIEW = {"ingested": st.success, "duplicate": st.warning, "error": st.error}


def _login() -> None:
    st.subheader(T.ADMIN_LOGIN_TITLE)
    with st.form("admin_login"):
        key = st.text_input(T.ADMIN_KEY_LABEL, type="password", help=T.ADMIN_LOGIN_HELP)
        submitted = st.form_submit_button(T.ADMIN_LOGIN, type="primary")
    if submitted:
        if not key.strip():
            st.error(T.ADMIN_KEY_EMPTY)
            return
        try:
            list_documents(key.strip())  # validates the key
        except ApiError as exc:
            st.error(exc.message)
            return
        st.session_state.admin_key = key.strip()
        st.rerun()


def _logout() -> None:
    for k in ("admin_key", "upload_results", "confirm_delete"):
        st.session_state.pop(k, None)


def _handle_auth_error(exc: ApiError) -> None:
    if exc.status == 401:
        _logout()
        st.rerun()
    st.error(exc.message)


def _upload_section(key: str) -> None:
    st.subheader(T.UPLOAD_TITLE)
    # Changing the widget key after an upload clears the selected files
    uploader_id = st.session_state.setdefault("uploader_id", 0)
    files = st.file_uploader(
        T.UPLOAD_LABEL, type=["pdf", "docx", "txt"], accept_multiple_files=True, key=f"uploader_{uploader_id}"
    )
    if st.button(T.UPLOAD_BUTTON, type="primary", disabled=not files, icon=":material/upload:"):
        payload = [(f.name, f.getvalue(), f.type or "application/octet-stream") for f in files]
        with st.spinner(T.UPLOAD_PROGRESS.format(n=fa(len(payload)))):
            try:
                result = upload_documents(key, payload)
            except ApiError as exc:
                _handle_auth_error(exc)
                return
        st.session_state.upload_results = result["results"]
        st.session_state.uploader_id += 1
        invalidate_health()
        st.rerun()

    for r in st.session_state.get("upload_results", []):
        suffix = T.UPLOAD_CHUNKS.format(n=fa(r["chunks"])) if r.get("chunks") else ""
        _STATUS_VIEW.get(r["status"], st.info)(r["message"] + suffix)


def _documents_section(key: str) -> None:
    head, refresh = st.columns([4, 1], vertical_alignment="bottom")
    head.subheader(T.DOCS_TITLE)
    if refresh.button(T.DOCS_REFRESH, icon=":material/refresh:", width="stretch"):
        st.rerun()

    try:
        docs = list_documents(key)
    except ApiError as exc:
        _handle_auth_error(exc)
        return

    if not docs:
        st.caption(T.DOCS_EMPTY)
        return
    st.caption(T.DOCS_COUNT.format(n=fa(len(docs))))

    widths = [4, 1.3, 2, 1.2]
    header = st.columns(widths)
    for col, title in zip(header, (T.DOCS_COL_NAME, T.DOCS_COL_CHUNKS, T.DOCS_COL_DATE, "")):
        col.markdown(f"**{title}**")

    for doc in docs:
        name, chunks, date, action = st.columns(widths, vertical_alignment="center")
        name.write(doc["filename"])
        chunks.write(fa(doc["chunks"]))
        date.write(fa_datetime(doc["uploaded_at"]))
        if action.button(T.DOCS_DELETE, key=f"del_{doc['doc_id']}", icon=":material/delete:"):
            st.session_state.confirm_delete = doc

    pending = st.session_state.get("confirm_delete")
    if pending:
        st.warning(T.DOCS_DELETE_CONFIRM.format(name=pending["filename"]))
        yes, no, _ = st.columns([1, 1, 3])
        if yes.button(T.DOCS_DELETE_YES, type="primary"):
            try:
                delete_document(key, pending["doc_id"])
            except ApiError as exc:
                _handle_auth_error(exc)
            st.session_state.pop("confirm_delete", None)
            invalidate_health()
            st.rerun()
        if no.button(T.DOCS_DELETE_NO):
            st.session_state.pop("confirm_delete", None)
            st.rerun()


def render_admin_page() -> None:
    st.title(T.ADMIN_TITLE)
    key = st.session_state.get("admin_key")
    if not key:
        _login()
        return

    with st.sidebar:
        if st.button(T.ADMIN_LOGOUT, icon=":material/logout:", width="stretch"):
            _logout()
            st.rerun()

    _upload_section(key)
    st.divider()
    _documents_section(key)


# ==================================================================================================
# frontend/app.py
# ==================================================================================================
def main() -> None:
    st.set_page_config(page_title=T.APP_TITLE, page_icon=":material/account_balance:", layout="centered")

    inject_style()
    navigation = st.navigation([
        st.Page(render_chat_page, title=T.NAV_CHAT, icon=":material/chat:", url_path="chat", default=True),
        st.Page(render_admin_page, title=T.NAV_ADMIN, icon=":material/folder_managed:", url_path="admin"),
    ])
    render_sidebar()
    navigation.run()


if __name__ == "__main__":
    main()
