"""Builds the two single-file versions of the project from the modular code:

    rag_server.py    <- app/*.py          (run:  python rag_server.py)
    frontend_app.py  <- frontend/**       (run:  python frontend_app.py)

The modular code stays the source of truth; re-run this after changing it:
    .venv/bin/python scripts/build_standalone.py
"""
import ast
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INTERNAL = {"app", "texts", "api_client", "config", "ui"}

HEADER = '''"""{title}

Single-file build of {src} — generated by scripts/build_standalone.py, do not edit by hand.
Settings are read from a .env file next to this file.

Run:  python {name}
"""
'''


class Module:
    def __init__(self, path: str, replace: list[tuple[str, str]] = (), regex: list[tuple[str, str]] = ()):
        self.path = path
        source = (ROOT / path).read_text(encoding="utf-8")
        tree = ast.parse(source)
        lines = source.splitlines()
        drop: set[int] = set()
        self.imports: list[ast.stmt] = []
        self.docstring = ast.get_docstring(tree)
        for i, node in enumerate(tree.body):
            is_doc = i == 0 and self.docstring is not None and isinstance(node, ast.Expr)
            is_import = isinstance(node, (ast.Import, ast.ImportFrom))
            if is_doc or is_import:
                drop.update(range(node.lineno - 1, node.end_lineno))
            if is_import and _top_module(node) not in INTERNAL:
                self.imports.append(node)
        body = "\n".join(line for n, line in enumerate(lines) if n not in drop)
        for old, new in replace:
            if old not in body:
                sys.exit(f"{path}: expected text not found, update build_standalone.py: {old!r}")
            body = body.replace(old, new)
        for pattern, new in regex:
            body = re.sub(pattern, new, body)
        self.body = re.sub(r"\n{3,}", "\n\n\n", body).strip("\n")

    def section(self) -> str:
        title = self.path + (f" — {self.docstring.splitlines()[0]}" if self.docstring else "")
        bar = "# " + "=" * 98
        return f"{bar}\n# {title}\n{bar}\n{self.body}"


def _top_module(node: ast.stmt) -> str:
    if isinstance(node, ast.ImportFrom):
        return (node.module or "").split(".")[0]
    return node.names[0].name.split(".")[0]


def render_imports(modules: list[Module], extra: list[str] = ()) -> str:
    plain: dict[str, set[str]] = {}  # top-level package -> "import x" lines
    froms: dict[str, list[str]] = {}  # module -> names in first-seen order
    nodes = [n for m in modules for n in m.imports] + [ast.parse(e).body[0] for e in extra]
    for node in nodes:
        if isinstance(node, ast.Import):
            for a in node.names:
                plain.setdefault(a.name, set()).add(f"import {a.name}" + (f" as {a.asname}" if a.asname else ""))
        else:
            names = froms.setdefault(node.module, [])
            for a in node.names:
                name = a.name + (f" as {a.asname}" if a.asname else "")
                if name not in names:
                    names.append(name)

    def group(stdlib: bool) -> list[str]:
        out = []
        for mod in sorted(set(plain) | set(froms), key=str.lower):
            if (mod.split(".")[0] in sys.stdlib_module_names) != stdlib:
                continue
            out += sorted(plain.get(mod, ()))
            if mod in froms:
                out.append(f"from {mod} import {', '.join(froms[mod])}")
        return out

    return "\n".join(group(True)) + "\n\n" + "\n".join(group(False))


def write(name: str, title: str, src: str, imports: str, sections: list[str]) -> None:
    text = HEADER.format(title=title, src=src, name=name) + imports + "\n\n\n" + "\n\n\n".join(sections) + "\n"
    ast.parse(text)  # fail the build, not the server, on a syntax error
    (ROOT / name).write_text(text, encoding="utf-8")
    print(f"wrote {name} ({len(text.splitlines())} lines)")


PARENT_FIX = ("Path(__file__).resolve().parent.parent", "Path(__file__).resolve().parent")


def build_backend() -> None:
    no_prefix = [(r"\bprompts\.", "")]
    modules = [
        Module("app/config.py", replace=[PARENT_FIX]),
        Module("app/persian.py"),
        Module("app/prompts.py"),
        Module("app/document_loader.py"),
        Module("app/rag_engine.py", regex=no_prefix),
        Module(
            "app/main.py",
            replace=[("MSG = prompts.MSG\n", ""), ('uvicorn.run("app.main:app",', "uvicorn.run(app,")],
            regex=no_prefix,
        ),
    ]
    write(
        "rag_server.py", "Persian RAG administrative assistant — backend (FastAPI + RAG engine).", "app/",
        render_imports(modules), [m.section() for m in modules],
    )


def build_frontend() -> None:
    no_client = [(r"\bapi_client\.", "")]
    texts = Module("frontend/texts.py")
    texts.body = f'class T:\n    """{texts.docstring}"""\n\n' + "\n".join(
        f"    {line}" if line.strip() else "" for line in texts.body.splitlines()
    )
    css = (ROOT / "frontend/assets/style.css").read_text(encoding="utf-8")
    style = Module("frontend/ui/style.py")
    style.body = (
        f'CSS = """\n{css.strip()}\n"""\n\n\n'
        "def inject_style() -> None:\n"
        '    st.html("<style>" + CSS + "</style>")'
    )
    style.path = "frontend/ui/style.py + frontend/assets/style.css"
    app = Module(
        "frontend/app.py",
        replace=[
            ("style.inject()", "inject_style()"),
            ("chat_page.render,", "render_chat_page,"),
            ("admin_page.render,", "render_admin_page,"),
            ("sidebar.render()", "render_sidebar()"),
        ],
    )
    app.docstring = None  # its "streamlit run app.py" hint doesn't apply here
    app.body = "def main() -> None:\n" + re.sub(r"\n{3,}", "\n\n", "\n".join(
        f"    {line}" if line.strip() else "" for line in app.body.splitlines()
    ))

    # frontend/.streamlit/config.toml can't travel with a single file, so it becomes CLI flags
    config = tomllib.loads((ROOT / "frontend/.streamlit/config.toml").read_text(encoding="utf-8"))
    flags = [
        (f"--{section}.{key}", str(value).lower() if isinstance(value, bool) else str(value))
        for section, items in config.items() for key, value in items.items()
    ]
    flag_lines = "".join(f'        "{k}", "{v}",\n' for k, v in flags)
    # Placed right after the config section, so the plain-python pass execs before any Streamlit code runs
    launcher = Module("frontend/config.py", replace=[PARENT_FIX])
    launcher.body += (
        "\n\n"
        'if __name__ == "__main__" and not runtime.exists():\n'
        "    # `python frontend_app.py` re-runs this file under Streamlit with the port/address from .env\n"
        "    os.execv(sys.executable, [\n"
        '        sys.executable, "-m", "streamlit", "run", __file__,\n'
        '        "--server.port", os.getenv("FRONTEND_PORT", "8501"),\n'
        '        "--server.address", os.getenv("FRONTEND_HOST", "0.0.0.0"),\n'
        f"{flag_lines}"
        "    ])"
    )
    app.body += '\n\n\nif __name__ == "__main__":\n    main()'

    modules = [
        launcher,
        texts,
        Module("frontend/ui/formatting.py"),
        Module("frontend/api_client.py"),
        style,
        Module("frontend/ui/sidebar.py", replace=[("def render()", "def render_sidebar()")], regex=no_client),
        Module("frontend/ui/chat_page.py", replace=[("def render()", "def render_chat_page()")], regex=no_client),
        Module(
            "frontend/ui/admin_page.py",
            replace=[("def render()", "def render_admin_page()"), ("sidebar.invalidate_health()", "invalidate_health()")],
            regex=no_client,
        ),
        app,
    ]
    write(
        "frontend_app.py", "Persian RAG administrative assistant — Streamlit UI.", "frontend/",
        render_imports(modules, extra=["import sys", "from streamlit import runtime"]), [m.section() for m in modules],
    )


if __name__ == "__main__":
    build_backend()
    build_frontend()
